In [1]:
import geopandas as gpd
from tqdm import tqdm  # barra de progresso (opcional)

In [2]:
RESULT_FOLDER = '/Users/fernandogomes/dev/LiDAR_produtos'

In [3]:
gdf_articulacao_17_20 = gpd.read_file("zip://data/SIRGAS_SHP_quadriculamdt.zip!/SIRGAS_SHP_quadriculamdt/")
gdf_articulacao_24 = gpd.read_file('results/folhas_sp_cortada.gpkg')
gdf_distritos = gpd.read_file('data/SIRGAS_GPKG_distrito.gpkg')

In [4]:
gdf_articulacao_24.to_crs(epsg=31983, inplace=True)

In [5]:
gdf_articulacao_17_20.set_crs(epsg=31983, inplace=True)

      qmdt_cod                                           geometry
0     3212-353  POLYGON ((329132.004 7367829.458, 329125.19 73...
1     3212-344  POLYGON ((328601.255 7367823.21, 328594.42 736...
2     3212-343  POLYGON ((328070.502 7367816.96, 328063.648 73...
3     3211-464  POLYGON ((327539.756 7367810.622, 327532.876 7...
4     3211-463  POLYGON ((327008.999 7367804.285, 327002.102 7...
...        ...                                                ...
5357  3234-241  POLYGON ((331960.582 7352864.136, 331967.325 7...
5358  3234-224  POLYGON ((333544.473 7353459.402, 333551.152 7...
5359  3336-444  POLYGON ((331725.429 7373051.662, 332256.363 7...
5360  3336-442  POLYGON ((331718.736 7373628.441, 332249.692 7...
5361  3336-414  POLYGON ((331712.043 7374205.219, 332243.02 73...

[5362 rows x 2 columns]

In [6]:
gdf_distritos.set_crs(epsg=31983, inplace=True)

,ds_nome,ds_codigo,ds_cd_sub,ds_subpref,ds_sigla,ds_areamt,ds_areakm,geometry
0,MANDAQUI,51,05,SANTANA-TUCURUVI,MAN,13249456.00,13.249000,"POLYGON ((333079.583 7408102.398, 333077.161 7..."
1,MOEMA,32,12,VILA MARIANA,MOE,9079516.00,9.080000,"POLYGON ((331290.13 7392111.284, 331324.217 73..."
2,ARTUR ALVIM,5,21,PENHA,AAL,6505750.00,6.506000,"POLYGON ((349420.638 7397694.618, 349423.468 7..."
3,IGUATEMI,33,30,SAO MATEUS,IGU,19434636.00,19.434999,"POLYGON ((350874.784 7389641.837, 350875.63 73..."
4,ITAIM BIBI,35,11,PINHEIROS,IBI,10026328.00,10.026000,"POLYGON ((327871.085 7386152.364, 327865.295 7..."
...,...,...,...,...,...,...,...,...
91,BUTANTA,12,10,BUTANTA,BUT,12952521.00,12.953000,"POLYGON ((322140.524 7393133.295, 322137.103 7..."
92,CACHOEIRINHA,13,04,CASA VERDE-CACHOEIRINHA,CAC,13571737.00,13.572000,"POLYGON ((330933.585 7402181.544, 330910.867 7..."
93,CAMBUCI,14,09,SE,CMB,3924676.75,3.925000,"POLYGON ((334806.666 7391501.308, 334783.054 7..."
94,CAMPO GRANDE,16,14,SANTO AMARO,CGR,12936654.00,12.937000,"POLYGON ((325612.963 7381815.938, 325634.233 7..."
95,CAMPO LIMPO,17,17,CAMPO LIMPO,CLM,12594803.00,12.595000,"POLYGON ((321408.128 7387296.041, 321422.038 7..."

In [7]:
gdf_distritos

,ds_nome,ds_codigo,ds_cd_sub,ds_subpref,ds_sigla,ds_areamt,ds_areakm,geometry
0,MANDAQUI,51,05,SANTANA-TUCURUVI,MAN,13249456.00,13.249000,"POLYGON ((333079.583 7408102.398, 333077.161 7..."
1,MOEMA,32,12,VILA MARIANA,MOE,9079516.00,9.080000,"POLYGON ((331290.13 7392111.284, 331324.217 73..."
2,ARTUR ALVIM,5,21,PENHA,AAL,6505750.00,6.506000,"POLYGON ((349420.638 7397694.618, 349423.468 7..."
3,IGUATEMI,33,30,SAO MATEUS,IGU,19434636.00,19.434999,"POLYGON ((350874.784 7389641.837, 350875.63 73..."
4,ITAIM BIBI,35,11,PINHEIROS,IBI,10026328.00,10.026000,"POLYGON ((327871.085 7386152.364, 327865.295 7..."
...,...,...,...,...,...,...,...,...
91,BUTANTA,12,10,BUTANTA,BUT,12952521.00,12.953000,"POLYGON ((322140.524 7393133.295, 322137.103 7..."
92,CACHOEIRINHA,13,04,CASA VERDE-CACHOEIRINHA,CAC,13571737.00,13.572000,"POLYGON ((330933.585 7402181.544, 330910.867 7..."
93,CAMBUCI,14,09,SE,CMB,3924676.75,3.925000,"POLYGON ((334806.666 7391501.308, 334783.054 7..."
94,CAMPO GRANDE,16,14,SANTO AMARO,CGR,12936654.00,12.937000,"POLYGON ((325612.963 7381815.938, 325634.233 7..."
95,CAMPO LIMPO,17,17,CAMPO LIMPO,CLM,12594803.00,12.595000,"POLYGON ((321408.128 7387296.041, 321422.038 7..."

In [8]:
gdf_distritos

,ds_nome,ds_codigo,ds_cd_sub,ds_subpref,ds_sigla,ds_areamt,ds_areakm,geometry
0,MANDAQUI,51,05,SANTANA-TUCURUVI,MAN,13249456.00,13.249000,"POLYGON ((333079.583 7408102.398, 333077.161 7..."
1,MOEMA,32,12,VILA MARIANA,MOE,9079516.00,9.080000,"POLYGON ((331290.13 7392111.284, 331324.217 73..."
2,ARTUR ALVIM,5,21,PENHA,AAL,6505750.00,6.506000,"POLYGON ((349420.638 7397694.618, 349423.468 7..."
3,IGUATEMI,33,30,SAO MATEUS,IGU,19434636.00,19.434999,"POLYGON ((350874.784 7389641.837, 350875.63 73..."
4,ITAIM BIBI,35,11,PINHEIROS,IBI,10026328.00,10.026000,"POLYGON ((327871.085 7386152.364, 327865.295 7..."
...,...,...,...,...,...,...,...,...
91,BUTANTA,12,10,BUTANTA,BUT,12952521.00,12.953000,"POLYGON ((322140.524 7393133.295, 322137.103 7..."
92,CACHOEIRINHA,13,04,CASA VERDE-CACHOEIRINHA,CAC,13571737.00,13.572000,"POLYGON ((330933.585 7402181.544, 330910.867 7..."
93,CAMBUCI,14,09,SE,CMB,3924676.75,3.925000,"POLYGON ((334806.666 7391501.308, 334783.054 7..."
94,CAMPO GRANDE,16,14,SANTO AMARO,CGR,12936654.00,12.937000,"POLYGON ((325612.963 7381815.938, 325634.233 7..."
95,CAMPO LIMPO,17,17,CAMPO LIMPO,CLM,12594803.00,12.595000,"POLYGON ((321408.128 7387296.041, 321422.038 7..."

In [9]:
# Garante que todos os GeoDataFrames estão no mesmo CRS
crs = gdf_distritos.crs
gdf_articulacao_17_20 = gdf_articulacao_17_20.to_crs(crs)
gdf_articulacao_24 = gdf_articulacao_24.to_crs(crs)

for _, distrito in tqdm(gdf_distritos.iterrows(), total=len(gdf_distritos)):
    nome_distrito = distrito["ds_nome"].replace(' ', '-')
    cod_distrito = distrito["ds_codigo"]

    folhas_17_20 = gdf_articulacao_17_20[gdf_articulacao_17_20.intersects(distrito.geometry)].copy()
    folhas_24 = gdf_articulacao_24[gdf_articulacao_24.intersects(distrito.geometry)].copy()

    files_2017 = ' '.join([f'{RESULT_FOLDER}/2017/LiDAR/buildings-{y}-2017-50cm.laz' for y in folhas_17_20.qmdt_cod.to_list()])
    files_2020 = ' '.join([f'{RESULT_FOLDER}/2020/LiDAR/buildings-{y}-2020-50cm.laz' for y in folhas_17_20.qmdt_cod.to_list()])
    files_2024 = ' '.join([f'{RESULT_FOLDER}/2024/LiDAR/buildings-{y}-2024-50cm.laz' for y in folhas_24.nome.to_list()])

    !pdal merge {files_2017} {RESULT_FOLDER}/2017/LiDAR-subs/{cod_distrito}-{nome_distrito}-buildings-50cm.laz
    !pdal merge {files_2020} {RESULT_FOLDER}/2020/LiDAR-subs/{cod_distrito}-{nome_distrito}-buildings-50cm.laz
    !pdal merge {files_2024} {RESULT_FOLDER}/2024/LiDAR-subs/{cod_distrito}-{nome_distrito}-buildings-50cm.laz

  0%|          | 0/96 [00:00<?, ?it/s]

100%|██████████| 96/96 [1:26:39<00:00, 54.17s/it]